In [2]:
import pandas as pd

data = pd.read_excel("ML Test BBW.xlsx")
data

,DIM4,DIM7,VatRate1,LocalAmt,EnteredBy,Username
0,BBW-AUOL,OP20-120,10,-134630.56,SV.M3API,M3 API for Apps
1,BBW-AUOL,OP20-101,0,-7022.82,SV.M3API,M3 API for Apps
2,BBW-AUOL,OP20-131,10,149.85,SV.M3API,M3 API for Apps
3,BBW-AUOL,OP20-131,10,-229.80,SV.M3API,M3 API for Apps
4,BBW-AUOL,OP20-131,10,-312.50,SV.M3API,M3 API for Apps
...,...,...,...,...,...,...
19997,BBW-AUOL,OP20-131,10,18.95,SV.M3API,M3 API for Apps
19998,BBW-AUOL,OP20-131,10,2251.53,SV.M3API,M3 API for Apps
19999,BBW-AUOL,OP20-101,0,-0.01,SV.M3API,M3 API for Apps
20000,BBW-AUOL,OP20-101,0,0.01,SV.M3API,M3 API for Apps
20001,BBW-AUOL,OP20-101,0,-0.03,SV.M3API,M3 API for Apps

In [3]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()
columns_to_encode = ['DIM4', 'DIM7', 'EnteredBy', 'Username']
onehot_encoder.fit(data[columns_to_encode])
encoded_data = onehot_encoder.transform(data[columns_to_encode]).toarray()

new_columns = onehot_encoder.get_feature_names_out(columns_to_encode)
encoded_df = pd.DataFrame(encoded_data, columns=new_columns)
print(encoded_df.head())

   DIM4_BBW-AUOL    DIM4_BBW-CSM     DIM4_BBW-DFO     DIM4_BBW-QVB     \
0              1.0              0.0              0.0              0.0
1              1.0              0.0              0.0              0.0
2              1.0              0.0              0.0              0.0
3              1.0              0.0              0.0              0.0
4              1.0              0.0              0.0              0.0

   DIM4_BBW-WCS     DIM4_BBW-WP      DIM7_OP20-101    DIM7_OP20-120    \
0              0.0              0.0              0.0              1.0
1              0.0              0.0              1.0              0.0
2              0.0              0.0              0.0              0.0
3              0.0              0.0              0.0              0.0
4              0.0              0.0              0.0              0.0

   DIM7_OP20-131    DIM7_OP20-132    DIM7_OP20-133    EnteredBy_MOVEX       \
0              0.0              0.0              0.0                   0.0
1              0.0              0.0              0.0                   0.0
2              1.0              0.0              0.0                   0.0
3              1.0              0.0              0.0                   0.0
4              1.0              0.0              0.0                   0.0

   EnteredBy_SV.M3API    EnteredBy_SV.MECAPI   \
0                   1.0                   0.0
1                   1.0                   0.0
2                   1.0                   0.0
3                   1.0                   0.0
4                   1.0                   0.0

   Username_M3 API for Apps                           \
0                                                1.0
1                                                1.0
2                                                1.0
3                                                1.0
4                                                1.0

   Username_M3 Auto Start Job                         \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   Username_MEC API
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

In [4]:
# Drop original columns
data_dropped = data.drop(columns=columns_to_encode)

# Concatenate the original DataFrame and the one-hot encoded DataFrame
final_data = pd.concat([data_dropped, encoded_df], axis=1)
final_data

,VatRate1,LocalAmt,DIM4_BBW-AUOL,DIM4_BBW-CSM,DIM4_BBW-DFO,DIM4_BBW-QVB,DIM4_BBW-WCS,DIM4_BBW-WP,DIM7_OP20-101,DIM7_OP20-120,DIM7_OP20-131,DIM7_OP20-132,DIM7_OP20-133,EnteredBy_MOVEX,EnteredBy_SV.M3API,EnteredBy_SV.MECAPI,Username_M3 API for Apps,Username_M3 Auto Start Job,Username_MEC API
0,10,-134630.56,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0,-7022.82,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,10,149.85,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,10,-229.80,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,10,-312.50,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19997,10,18.95,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
19998,10,2251.53,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
19999,0,-0.01,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
20000,0,0.01,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
20001,0,-0.03,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [5]:
actual_columns = final_data.columns.tolist()
actual_columns

['VatRate1',
 'LocalAmt',
 'DIM4_BBW-AUOL  ',
 'DIM4_BBW-CSM   ',
 'DIM4_BBW-DFO   ',
 'DIM4_BBW-QVB   ',
 'DIM4_BBW-WCS   ',
 'DIM4_BBW-WP    ',
 'DIM7_OP20-101  ',
 'DIM7_OP20-120  ',
 'DIM7_OP20-131  ',
 'DIM7_OP20-132  ',
 'DIM7_OP20-133  ',
 'EnteredBy_MOVEX     ',
 'EnteredBy_SV.M3API  ',
 'EnteredBy_SV.MECAPI ',
 'Username_M3 API for Apps                         ',
 'Username_M3 Auto Start Job                       ',
 'Username_MEC API                                 ']

In [6]:
from sklearn.model_selection import train_test_split

x = final_data[["VatRate1", "DIM4_BBW-AUOL  ", "DIM4_BBW-CSM   ",
"DIM4_BBW-DFO   ", "DIM4_BBW-QVB   ", "DIM4_BBW-WCS   ",
"DIM4_BBW-WP    ", "DIM7_OP20-101  ", "DIM7_OP20-120  ",
"DIM7_OP20-131  ", "DIM7_OP20-132  ", "DIM7_OP20-133  ",
"EnteredBy_MOVEX     ", "EnteredBy_SV.M3API  ", "EnteredBy_SV.MECAPI ",
"Username_M3 API for Apps                         ",
"Username_M3 Auto Start Job                       ",
"Username_MEC API                                 "]]
y = final_data["LocalAmt"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_test

array([[ 0.54169011, -0.49137175, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301],
       [ 0.54169011, -0.49137175, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301],
       [ 0.54169011,  2.03511904, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301],
       ...,
       [ 0.54169011, -0.49137175, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301],
       [ 0.54169011, -0.49137175, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301],
       [-1.84607394,  2.03511904, -0.43133509, ...,  0.04034282,
        -0.03261232, -0.02372301]])

In [8]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)
y_pred = lr_model.predict(x_test)

pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

            y_pred   y_test
4801  -2413.486491 -2914.77
14731 -2444.486491   -86.93
4889  -2720.986491 -2859.40
13889  4893.513509     0.03
9325  -1951.486491  -619.44
...            ...      ...
17303 -1987.986491    14.50
4864  -2572.486491 -2881.53
7452    662.888509    31.77
12342   626.388509   239.20
8956   4893.513509  6276.85

[4001 rows x 2 columns]